# Generated by Django 5.0.7 on 2024-08-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
